export const MODE = "MODE";

export const APP_URL = "APP_URL";
export const FE_APP_URL = "FE_APP_URL";
export const ADMIN_PASSWORD = "ADMIN_PASSWORD";

export const JWT_SECRET_KEY = "JWT_SECRET_KEY";
export const JWT_EXPIRATION = "JWT_EXPIRATION";

export const REDIS_HOST = "REDIS_HOST";
export const REDIS_PORT = "REDIS_PORT";
export const REDIS_PASSWORD = "REDIS_PASSWORD";

export const SMTP_HOST = "SMTP_HOST";
export const SMTP_PORT = "SMTP_PORT";
export const SMTP_USER = "SMTP_USER";
export const SMTP_PASSWORD = "SMTP_PASSWORD";
export const SMTP_FROM = "SMTP_FROM";

export const IMAP_HOST = "IMAP_HOST";
export const IMAP_PORT = "IMAP_PORT";
export const IMAP_USER = "IMAP_USER";
export const IMAP_PASSWORD = "IMAP_PASSWORD";

export const AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID";
export const AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY";
export const AWS_S3_BUCKET = "AWS_S3_BUCKET";

export const GOOGLE_MAPS_API_KEY = "GOOGLE_MAPS_API_KEY";
export const GOOGLE_MAPS_LANGUAGE = "GOOGLE_MAPS_LANGUAGE";

export const OPENAI_API_KEY = "OPENAI_API_KEY";
export const PERPLEXITY_API_KEY = "PERPLEXITY_API_KEY";

export const GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS";

export const SYSTEM_SETTING_CONFIRMATION_URL = "SYSTEM_SETTING_CONFIRMATION_URL";
export const SYSTEM_SETTING_SUUMO_SUBCATCH_URL = "SYSTEM_SETTING_SUUMO_SUBCATCH_URL";
export const SYSTEM_SETTING_THOUSAND_WORDS_MASTER_DATA_URL = "SYSTEM_SETTING_THOUSAND_WORDS_MASTER_DATA_URL";
